In [16]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt
import pandas_geojson

In [6]:
# load in housing data with necessary zips
housing_data = pd.read_csv("Resources/Clean/San_Diego_Housing_Data.csv", index_col=0)
housing_data.reset_index(inplace=True)
housing_data

# get necessary zip
zipcodes_df = pd.DataFrame(housing_data['Zip Code'])
zipcodes_df.rename(columns = {'Zip Code':'zipcode'}, inplace = True)
zipcodes_df

# Create geo tables
schools = pd.read_csv("Resources/Clean/San_Diego_School_Data.csv")
businesses = pd.read_csv("Resources/Clean/San_Diego_Markets.csv")
transit = pd.read_csv("Resources/Clean/San_Diego_Transit.csv")
parks = pd.read_csv("Resources/Clean/San_Diego_Parks.csv")
hospitals = pd.read_csv("Resources/Clean/San_Diego_Hospital_Data.csv")

In [7]:
# hospitals Geos
hospital_geos = hospitals[['name','lat','lng','zipcode']]
hospital_geos['resource'] = 'hospital'
hospital_geos = hospital_geos.set_index('zipcode')
hospital_geos

                                   name        lat         lng  resource
zipcode
91911      Bayview Hosp & Mental System  32.617520 -117.071364  hospital
91911         Sharp Chula Vista Med Ctr  32.619391 -117.022284  hospital
91942          Sharp Grossmont Hospital  32.781653 -117.008397  hospital
91950          Paradise Valley Hospital  32.685113 -117.082885  hospital
92024    Scripps Mem Hospital-Encinitas  33.038342 -117.284453  hospital
92025            Palomar Medical Center  33.124859 -117.075823  hospital
92028                Fallbrook Hospital  33.380736 -117.244647  hospital
92037         Scripps Mem Hosp-La Jolla  32.885154 -117.225538  hospital
92037            Scripps Green Hospital  32.897036 -117.242773  hospital
92055                    Naval Hospital  33.317842 -117.320512  hospital
92056           Tri-City Medical Center  33.185648 -117.290436  hospital
92064                 Pomerado Hospital  32.997673 -117.055405  hospital
92103        Continental Rehab Hospital  32.749746 -117.159794  hospital
92103            Scripps Mercy Hospital  32.751089 -117.160556  hospital
92103      Univ of CA San Diego Med Ctr  32.754270 -117.166135  hospital
92103                 San Diego Hospice  32.758465 -117.163698  hospital
92104        Kindred Hospital-San Diego  32.756350 -117.144261  hospital
92105     Promise Hospital of San Diego  32.749504 -117.076742  hospital
92110     San Diego Cnty Psych Hospital  32.753724 -117.201971  hospital
92118           Sharp Coronado Hospital  32.694447 -117.168661  hospital
92120        Kaiser Foundation Hospital  32.791613 -117.095405  hospital
92120      Alvarado Hosp Medical Center  32.776641 -117.057319  hospital
92123           Sharp Memorial Hospital  32.799521 -117.154603  hospital
92123     Rady Children Hosp & Hlth Ctr  32.797758 -117.151407  hospital
92123         Sharp Mary Birch Hospital  32.798373 -117.155060  hospital
92128         Aurora San Diego Hospital  32.991325 -117.074949  hospital
92134              Naval Medical Center  32.727424 -117.145341  hospital
92161    VA San Diego Healthcare System  32.875130 -117.232388  hospital
92562     Rancho Springs Medical Center  33.559100 -117.183965  hospital
92595      Inland Valley Medical Center  33.591713 -117.237659  hospital
92651        South Coast Medical Center  33.500257 -117.741942  hospital
92653    Saddleback Memorial Med Center  33.609325 -117.708930  hospital
92673     Saddleback Mem Medical Center  33.457484 -117.649924  hospital
92691    Children's Hospital at Mission  33.561015 -117.665394  hospital
92691                  Mission Hospital  33.561015 -117.665394  hospital

In [8]:
# Schools Geos
school_geos = schools[['name','lat','lng','zipcode']]
school_geos['resource'] = 'school'
school_geos = school_geos.set_index('zipcode')
school_geos

C:\Users\Adam\AppData\Local\Temp\ipykernel_28712\1105140812.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  school_geos['resource'] = 'school'

                                        name        lat         lng resource
zipcode
92037            Bird Rock Elementary School  32.811186 -117.263065   school
92093                     Preuss School Ucsd  32.878454 -117.229467   school
92037             La Jolla Elementary School  32.839236 -117.271699   school
92037         Torrey Pines Elementary School  32.859286 -117.242970   school
92037                   La Jolla High School  32.832408 -117.264719   school
...                                      ...        ...         ...      ...
92024              San Dieguito High Academy  33.037340 -117.274455   school
92024          Ocean Knoll Elementary School  33.039846 -117.277131   school
92024    Paul Ecke-Central Elementary School  33.057975 -117.298047   school
92024                Oak Crest Middle School  33.043177 -117.265476   school
91901                    The Heights Charter  32.835301 -116.755216   school

[247 rows x 4 columns]

In [9]:
# Business Geos
business_geos = businesses[['name','lat','lng','zipcode']]
business_geos['resource'] = 'business'
business_geos = business_geos.set_index('zipcode')
business_geos

C:\Users\Adam\AppData\Local\Temp\ipykernel_28712\732278148.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  business_geos['resource'] = 'business'

                           name        lat         lng  resource
zipcode
91910      Smart & Final Extra!  32.639000 -117.050924  business
91910    Sprouts Farmers Market  32.627807 -117.074994  business
91911      Carnival Supermarket  32.621859 -117.072892  business
91910            Target Grocery  32.653616 -117.065593  business
91910           99 Ranch Market  32.629342 -117.040931  business
...                         ...        ...         ...       ...
92154          El Picador Foods  32.573865 -117.055439  business
92173          Liva Distributor  32.568932 -117.064476  business
92173          La Bodega Market  32.552844 -117.042370  business
92173      Pancho Villa Mercado  32.561686 -117.063112  business
92173             Family Dollar  32.548929 -117.034492  business

[468 rows x 4 columns]

In [10]:
# Transit Geos

transit_geos = transit[['stop_name','lat','lng','Zip Code']]
transit_geos['resource'] = 'transit'
transit_geos.rename(columns = {'Zip Code':'zipcode'}, inplace = True)
transit_geos.rename(columns = {'stop_name':'name'}, inplace = True)
transit_geos = transit_geos.set_index('zipcode')
transit_geos

                                     name        lat         lng resource
zipcode
91941                Allison Av & Palm Av  32.765915 -117.019588  transit
91941          La Mesa Bl & University Av  32.767805 -117.015427  transit
91977          Sweetwater Rd & Jamacha Rd  32.714228 -117.012800  transit
91941                La Mesa Bl & Glen St  32.769344 -117.011003  transit
91977             Orville St & Brucker Av  32.709168 -117.009255  transit
...                                   ...        ...         ...      ...
92008    Plaza Camino Real Transit Center  33.178276 -117.336525  transit
92057         San Luis Rey Transit Center  33.254410 -117.298129  transit
92075                Solana Beach Station  32.992937 -117.271067  transit
92092             Sorrento Valley Station  32.902813 -117.225088  transit
92083                Vista Transit Center  33.203240 -117.245070  transit

[6116 rows x 4 columns]

In [11]:
# Park Geos
park_geos = parks[['name','lat','lng','postcode']]
park_geos.rename(columns = {'postcode':'zipcode'}, inplace = True)
park_geos['resource'] = 'park'
park_geos = park_geos.set_index('zipcode')
park_geos

C:\Users\Adam\AppData\Local\Temp\ipykernel_28712\1421351039.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  park_geos.rename(columns = {'postcode':'zipcode'}, inplace = True)
C:\Users\Adam\AppData\Local\Temp\ipykernel_28712\1421351039.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  park_geos['resource'] = 'park'

                                    name        lat         lng resource
zipcode
91901                     Wright's Field  32.819494 -116.763489     park
91901                        Viejas Park  32.842437 -116.704128     park
91901            Loveland Fishing Access  32.799750 -116.760434     park
91902    Sweetwater Summit Regional Park  32.682508 -117.002547     park
91902             Sweetwater County Park  32.682592 -117.001904     park
...                                  ...        ...         ...      ...
92763           Trestles Beach Trailhead  33.395758 -117.591568     park
92051                     Rock Formation  33.402802 -117.551148     park
92763                         San Onofre  33.389572 -117.593152     park
92763           Trestles Beach Trailhead  33.396085 -117.591365     park
92763                     Trestles Beach  33.385308 -117.593936     park

[1386 rows x 4 columns]

In [12]:
clean_geos_all = pd.concat([hospital_geos,school_geos, business_geos, transit_geos, park_geos])
clean_geos_all

                                   name        lat         lng  resource
zipcode
91911      Bayview Hosp & Mental System  32.617520 -117.071364  hospital
91911         Sharp Chula Vista Med Ctr  32.619391 -117.022284  hospital
91942          Sharp Grossmont Hospital  32.781653 -117.008397  hospital
91950          Paradise Valley Hospital  32.685113 -117.082885  hospital
92024    Scripps Mem Hospital-Encinitas  33.038342 -117.284453  hospital
...                                 ...        ...         ...       ...
92763          Trestles Beach Trailhead  33.395758 -117.591568      park
92051                    Rock Formation  33.402802 -117.551148      park
92763                        San Onofre  33.389572 -117.593152      park
92763          Trestles Beach Trailhead  33.396085 -117.591365      park
92763                    Trestles Beach  33.385308 -117.593936      park

[8252 rows x 4 columns]

In [13]:
coords = clean_geos_all[['lat', 'lng']].values
coords

array([[  32.6175204, -117.0713635],
       [  32.6193909, -117.0222837],
       [  32.7816526, -117.0083968],
       ...,
       [  33.3895721, -117.5931518],
       [  33.3960846, -117.5913646],
       [  33.3853075, -117.5939359]])

In [14]:
clean_geos_all.reset_index(inplace = True)
new_df = clean_geos_all[clean_geos_all.zipcode.isin(zipcodes_df.zipcode)]

In [15]:
new_df.groupby(['resource']).count()

          zipcode  name   lat   lng
resource
business      423   423   423   423
hospital       25    25    25    25
park         1245  1245  1245  1245
school        245   245   245   245
transit      5439  5439  5439  5439

In [21]:
# Create geoJSON variable
geo_json = to_geojson(df=new_df, lat='lat', lon='lng',
                 properties=['name','resource'])

#Write the geoJSON file
pandas_geojson.write_geojson(geo_json, filename='San_Diego_Amenities.geojson', indent=4)