In [1]:
# Import dependencies
import pandas as pd
filepath = "Resources/Clean/San_Diego_Housing_Data.csv"

# Read in the Dataframe
df = pd.read_csv(filepath, index_col=0)
df.head()

,Households_Total,"Households_Total_Less than $10,000","Households_Total_$10,000 to $14,999","Households_Total_$15,000 to $24,999","Households_Total_$25,000 to $34,999","Households_Total_$35,000 to $49,999","Households_Total_$50,000 to $74,999","Households_Total_$75,000 to $99,999","Households_Total_$100,000 to $149,999","Households_Total_$150,000 to $199,999",...,"Nonfamily households_Total_$25,000 to $34,999","Nonfamily households_Total_$35,000 to $49,999","Nonfamily households_Total_$50,000 to $74,999","Nonfamily households_Total_$75,000 to $99,999","Nonfamily households_Total_$100,000 to $149,999","Nonfamily households_Total_$150,000 to $199,999","Nonfamily households_Total_$200,000 or more",Nonfamily households_Median income (dollars),Nonfamily households_Mean income (dollars),Nonfamily households_PERCENT ALLOCATED_Nonfamily income in the past 12 months
Geographic Area Name,,,,,,,,,,,,,,,,,,,,,
91901,6150.0,148.0,62.0,326.0,646.0,492.0,578.0,1009.0,1218.0,824.0,...,366.0,232.0,218.0,197.0,193.0,52.0,31.0,43523.0,62711.0,22.2
91902,6045.0,169.0,36.0,187.0,308.0,459.0,731.0,864.0,1396.0,907.0,...,237.0,336.0,172.0,245.0,327.0,137.0,130.0,70469.0,111325.0,53.8
91906,1282.0,59.0,35.0,95.0,162.0,347.0,144.0,82.0,229.0,128.0,...,33.0,152.0,26.0,3.0,0.0,16.0,0.0,35991.0,37850.0,38.0
91910,24599.0,1082.0,1328.0,1648.0,2263.0,2558.0,4182.0,3247.0,4256.0,2066.0,...,766.0,814.0,1232.0,746.0,623.0,164.0,198.0,40825.0,56747.0,44.1
91911,25145.0,805.0,1308.0,1936.0,2439.0,2791.0,4702.0,3043.0,4903.0,2012.0,...,818.0,687.0,760.0,414.0,307.0,78.0,34.0,33231.0,45098.0,45.0

In [2]:
df.reset_index(inplace=True)
df = df.rename(columns = {'Geographic Area Name': 'Zipcode'})
df.head()

,Zipcode,Households_Total,"Households_Total_Less than $10,000","Households_Total_$10,000 to $14,999","Households_Total_$15,000 to $24,999","Households_Total_$25,000 to $34,999","Households_Total_$35,000 to $49,999","Households_Total_$50,000 to $74,999","Households_Total_$75,000 to $99,999","Households_Total_$100,000 to $149,999",...,"Nonfamily households_Total_$25,000 to $34,999","Nonfamily households_Total_$35,000 to $49,999","Nonfamily households_Total_$50,000 to $74,999","Nonfamily households_Total_$75,000 to $99,999","Nonfamily households_Total_$100,000 to $149,999","Nonfamily households_Total_$150,000 to $199,999","Nonfamily households_Total_$200,000 or more",Nonfamily households_Median income (dollars),Nonfamily households_Mean income (dollars),Nonfamily households_PERCENT ALLOCATED_Nonfamily income in the past 12 months
0,91901,6150.0,148.0,62.0,326.0,646.0,492.0,578.0,1009.0,1218.0,...,366.0,232.0,218.0,197.0,193.0,52.0,31.0,43523.0,62711.0,22.2
1,91902,6045.0,169.0,36.0,187.0,308.0,459.0,731.0,864.0,1396.0,...,237.0,336.0,172.0,245.0,327.0,137.0,130.0,70469.0,111325.0,53.8
2,91906,1282.0,59.0,35.0,95.0,162.0,347.0,144.0,82.0,229.0,...,33.0,152.0,26.0,3.0,0.0,16.0,0.0,35991.0,37850.0,38.0
3,91910,24599.0,1082.0,1328.0,1648.0,2263.0,2558.0,4182.0,3247.0,4256.0,...,766.0,814.0,1232.0,746.0,623.0,164.0,198.0,40825.0,56747.0,44.1
4,91911,25145.0,805.0,1308.0,1936.0,2439.0,2791.0,4702.0,3043.0,4903.0,...,818.0,687.0,760.0,414.0,307.0,78.0,34.0,33231.0,45098.0,45.0

In [3]:
# Drop 'San Diego CA, California' from zipcodes
df['Zipcode'].values

array(['91901', '91902', '91905', '91906', '91910', '91911', '91913',
       '91914', '91915', '91916', '91917', '91931', '91932', '91934',
       '91935', '91941', '91942', '91945', '91948', '91950', '91962',
       '91963', '91977', '91978', '92003', '92004', '92007', '92008',
       '92009', '92010', '92011', '92014', '92019', '92020', '92021',
       '92024', '92025', '92026', '92027', '92028', '92029', '92036',
       '92037', '92040', '92054', '92055', '92056', '92057', '92058',
       '92059', '92060', '92061', '92064', '92065', '92066', '92067',
       '92069', '92070', '92071', '92075', '92078', '92081', '92082',
       '92083', '92084', '92086', '92091', '92101', '92102', '92103',
       '92104', '92105', '92106', '92107', '92108', '92109', '92110',
       '92111', '92113', '92114', '92115', '92116', '92117', '92118',
       '92119', '92120', '92121', '92122', '92123', '92124', '92126',
       '92127', '92128', '92129', '92130', '92131', '92139', '92145',
       '92154', '92173', '92672', 'San Diego County, California'],
      dtype=object)

In [4]:
# Remove SD from Zipcodes
new_df = df.drop(df.index[-1])
new_df.tail()

,Zipcode,Estimate_Households_Total,"Estimate_Households_Total_Less than $10,000","Estimate_Households_Total_$10,000 to $14,999","Estimate_Households_Total_$15,000 to $24,999","Estimate_Households_Total_$25,000 to $34,999","Estimate_Households_Total_$35,000 to $49,999","Estimate_Households_Total_$50,000 to $74,999","Estimate_Households_Total_$75,000 to $99,999","Estimate_Households_Total_$100,000 to $149,999",...,"Estimate_Percent renter-occupied housing units_Occupied housing units_MONTHLY HOUSING COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS_$50,000 to $74,999","Estimate_Percent renter-occupied housing units_Occupied housing units_MONTHLY HOUSING COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS_$50,000 to $74,999_Less than 20 percent","Estimate_Percent renter-occupied housing units_Occupied housing units_MONTHLY HOUSING COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS_$50,000 to $74,999_20 to 29 percent","Estimate_Percent renter-occupied housing units_Occupied housing units_MONTHLY HOUSING COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS_$50,000 to $74,999_30 percent or more","Estimate_Percent renter-occupied housing units_Occupied housing units_MONTHLY HOUSING COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS_$75,000 or more","Estimate_Percent renter-occupied housing units_Occupied housing units_MONTHLY HOUSING COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS_$75,000 or more_Less than 20 percent","Estimate_Percent renter-occupied housing units_Occupied housing units_MONTHLY HOUSING COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS_$75,000 or more_20 to 29 percent","Estimate_Percent renter-occupied housing units_Occupied housing units_MONTHLY HOUSING COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS_$75,000 or more_30 percent or more",Estimate_Percent renter-occupied housing units_Occupied housing units_MONTHLY HOUSING COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS_Zero or negative income,Estimate_Percent renter-occupied housing units_Occupied housing units_MONTHLY HOUSING COSTS AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS_No cash rent
96,92139,10066,3.0,1.8,5.6,8.2,11.2,19.5,14.8,23.3,...,22.1,0.4,7.4,14.3,32.5,16.1,13.7,2.7,1.8,6.7
97,92145,519,1.3,0.0,0.0,0.0,0.0,11.4,8.3,7.9,...,25.4,0,25.4,0,28.8,16.9,11.9,0,0,45.8
98,92154,22634,3.1,3.8,6.6,8.0,13.6,18.2,14.6,19.4,...,20.6,1.8,3.9,14.9,29.8,10.7,15.5,3.6,0.6,1.3
99,92173,8160,7.0,11.1,10.5,8.2,14.6,16.6,12.2,12.1,...,14.9,2,7.2,5.7,17.8,11.2,6.3,0.3,3.1,1.3
100,92672,14480,4.5,3.9,4.1,6.2,9.1,13.2,14.3,17.4,...,15.3,0.4,3.9,11,45.8,19.6,16.8,9.5,2.1,4.4

In [5]:
# Remove Outliers
new_df = new_df.drop(new_df.index[97], axis=0)
new_df = new_df.drop(new_df.index[50], axis=0)
new_df = new_df.drop(new_df.index[18], axis=0)

In [6]:
# Convert objects to floats (In hopes to transform testing data for machine learning model)
new_df['Estimate_Households_Median income (dollars)'] = new_df['Estimate_Households_Median income (dollars)'].astype('float')

new_df['Estimate_Families_Median income (dollars)'] = new_df['Estimate_Households_Median income (dollars)'].astype('float')

new_df['Estimate_Families_Mean income (dollars)'] = new_df['Estimate_Households_Median income (dollars)'].astype('float')

In [7]:
testing_df = new_df[['Estimate_Households_Total','Estimate_Households_Median income (dollars)', 'Estimate_Households_Mean income (dollars)', 'Estimate_Families_Median income (dollars)','Estimate_Families_Mean income (dollars)', 'Estimate_Occupied housing units_Occupied housing units']]
testing_df.tail()

,Estimate_Households_Total,Estimate_Households_Median income (dollars),Estimate_Households_Mean income (dollars),Estimate_Families_Median income (dollars),Estimate_Families_Mean income (dollars),Estimate_Occupied housing units_Occupied housing units
95,12127,137987.0,168712,137987.0,137987.0,12127
96,10066,75576.0,88632,75576.0,75576.0,10066
98,22634,70846.0,84589,70846.0,70846.0,22634
99,8160,48967.0,64162,48967.0,48967.0,8160
100,14480,89029.0,134029,89029.0,89029.0,14480

In [8]:
testing_df.dtypes.value_counts

<bound method IndexOpsMixin.value_counts of Estimate_Households_Total                                   int64
Estimate_Households_Median income (dollars)               float64
Estimate_Households_Mean income (dollars)                   int64
Estimate_Families_Median income (dollars)                 float64
Estimate_Families_Mean income (dollars)                   float64
Estimate_Occupied housing units_Occupied housing units      int64
dtype: object>