In [1]:
# importing dependencies
import pandas as pd
import glob
import os

In [2]:
# setting path
files = os.path.join("Resources/RAW/Schools/greatschools*.csv")

In [3]:
#list of merged files returned
files = glob.glob(files)

In [4]:
# joining files 
school_df = pd.concat(map(pd.read_csv, files), ignore_index=True)

school_df

,circle-rating--small,rating-circle-small,scale,name,address,tablescraper-selected-row 2,tablescraper-selected-row 3,tablescraper-selected-row 4,tablescraper-selected-row href,tablescraper-selected-row 6,tablescraper-selected-row href 2,name href,tablescraper-selected-row
0,7.0,/10,Above average,The Heights Charter,"2710 Alpine Boulevard, Suite E, Alpine, CA, 91901",K-8,244,15:1,https://www.greatschools.org/california/alpine...,Dehesa Elementary School District,https://www.greatschools.org/california/alpine...,NaN,NaN
1,6.0,/10,Average,Boulder Oaks Elementary School,"2320 Tavern Road, Alpine, CA, 91901",1-5,333,24:1,https://www.greatschools.org/california/alpine...,Alpine Union Elementary School District,https://www.greatschools.org/california/alpine...,NaN,NaN
2,6.0,/10,Average,Joan Macqueen Middle School,"2001 Tavern Road, Alpine, CA, 91901",6-8,438,20:1,https://www.greatschools.org/california/alpine...,Alpine Union Elementary School District,https://www.greatschools.org/california/alpine...,NaN,NaN
3,6.0,/10,Average,Shadow Hills Elementary School,"8770 Harbison Canyon Road, Alpine, CA, 91901",K-5,387,20:1,https://www.greatschools.org/california/alpine...,Alpine Union Elementary School District,https://www.greatschools.org/california/alpine...,NaN,NaN
4,4.0,/10,Below average,Alpine Elementary School,"1850 Alpine Boulevard, Alpine, CA, 91901",1-5,158,20:1,https://www.greatschools.org/california/alpine...,Alpine Union Elementary School District,https://www.greatschools.org/california/alpine...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
849,2.0,/10,Below average,Major General Raymond Murray High School,"215 North Melrose Drive, Vista, CA, 92083",10-12,178.0,11:1,NaN,Vista Unified School District,NaN,https://www.greatschools.org/california/vista/...,Public district
850,1.0,/10,Below average,Alta Vista High (Continuation) School,"1575 Bonair Road, Vista, CA, 92084",9-12,113.0,8:1,NaN,Vista Unified School District,NaN,https://www.greatschools.org/california/vista/...,Public district
851,NaN,NaN,Currently unrated,Vista Adult,"510 Sunset Drive, Vista, CA, 92081",Ungraded,NaN,NaN,NaN,Vista Unified School District,NaN,https://www.greatschools.org/california/vista/...,Public district
852,NaN,NaN,Currently unrated,National University Academy,"2030 University Drive, Vista, CA, 92083",K-12,39.0,19:1,NaN,Lakeside Union Elementary School District,NaN,https://www.greatschools.org/california/vista/...,Public charter
853,NaN,NaN,Currently unrated,Olive Elementary School,"836 Olive Avenue, Vista, CA, 92083",K-5,348.0,23:1,NaN,Vista Unified School District,NaN,https://www.greatschools.org/california/vista/...,Public district

In [5]:
# Separate Zpcodes into a new column and rename student count column 
school_df['zipcode'] = school_df['address'].str[-5:]
school_df['student_count'] = school_df['tablescraper-selected-row 3']

# Drop columns with irrelevant data
school_df.drop(['rating-circle-small','tablescraper-selected-row 2','tablescraper-selected-row 3','tablescraper-selected-row 4','tablescraper-selected-row href','tablescraper-selected-row 6','tablescraper-selected-row href 2','name href','tablescraper-selected-row','address'],axis=1,inplace=True)
school_df = school_df.set_index("zipcode")
school_df.dropna(axis=0,how='any',inplace=True)

# Convert datatypes
school_df['student_count'] = school_df['student_count'].astype('int64')


school_df

,circle-rating--small,scale,name,student_count
zipcode,,,,
91901,7.0,Above average,The Heights Charter,244
91901,6.0,Average,Boulder Oaks Elementary School,333
91901,6.0,Average,Joan Macqueen Middle School,438
91901,6.0,Average,Shadow Hills Elementary School,387
91901,4.0,Below average,Alpine Elementary School,158
...,...,...,...,...
92083,3.0,Below average,Bobier Elementary School,659
92084,3.0,Below average,Rancho Minerva Middle School,717
92083,3.0,Below average,Vista Academy Of Visual And Performing Arts,611
92083,2.0,Below average,Major General Raymond Murray High School,178
92084,1.0,Below average,Alta Vista High (Continuation) School,113

In [6]:
# exporting file
from pathlib import Path

filepath = Path("Resources/Clean/schools.csv")
school_df.to_csv(filepath)